### ISSUE TITLE
API changed

### ISSUE THREAD

**Issue by marcelverdult** [RobertD502/lavviebotaio#1]
Hi,
since they published a new App for the Lavviebot the API URLs changed :-(
I tried packet capture on my phone and i see connections to amazon aws.
maybe you could upgrade this project?
greets
Marcel

**Comment by RobertD502** [comment]
@marcelverdult Yes, the API endpoints changed when they switched over to the new app. I've been busy with another Home Assistant integration so I haven't had a chance to make changes to the new API. The new API uses a single end point with various bodies for the different pages. I will look into it once I have some more time. Glad to see there are other Lavviebot users that have been using this. I thought i was the only one.

**Comment by marcelverdult** [comment]
ok i'll have to wait than. Yeah i love it! Would be great to get the usage notification to start the robot vacuum after cats distributed litter everywhere ;-)

**Comment by RobertD502** [comment]
Are you referring to the IoT usage Log found in the cat tab of the app or the cat log found under IoT device?

**Comment by RobertD502** [comment]
@marcelverdult 
Library and Home Assistant integration have been rewritten.
