### ISSUE TITLE
feature: Daily information

### ISSUE THREAD

**Issue by josueggh** [RobertD502/lavviebotaio#6]
Is it possible to obtain daily information from cats? (hours of sleep, walking, etc.)

How I can help you to bring this to the API.

**Comment by RobertD502** [comment]
> Is it possible to obtain daily information from cats? (hours of sleep, walking, etc.)
> 
> 
> 
> How I can help you to bring this to the API.

Do you use a LavvieTAG?

**Comment by josueggh** [comment]
yes, I have the LavvieTag :)

**Comment by RobertD502** [comment]
Could you possibly send me a DM on Discord (handle is the same as my username here) so I can give you an email to add to your PurrSong household? This will allow me to not only match up the health statistics with the lavvietags but also see how the battery information is presented by their API(I don't have that information integrated into Home Assistant as I don't have a Tag and haven't spoken to anyone that has one, but would love to get that added).

**Comment by josueggh** [comment]
I sent you a request.
